feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      DEVICE-SERVICE:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2